### ISSUE TITLE
onClick selectedtimeslots 

### ISSUE THREAD

**Issue by Hamatek** [lrojas94/react-timeslot-calendar#23]
nice react calendar, it works  well but how about passing up the selectedtimeslots , how can my parent component know what time slots user selected or unselected ?

**Comment by lrojas94** [comment]
Great point! Will be added in the next update! Thanks a lot

**Comment by VikramK** [comment]
What is the ETA for the next release with this enhancement?

**Comment by lrojas94** [comment]
Hopefully, we're planning to release it next week at the latter.

**Comment by lrojas94** [comment]
v0.2.0 is now up @VikramK @Hamatek. Please test it out and close this issue if it's what you guys needed!

**Comment by Hamatek** [comment]
looking good to me, can close this issue

**Comment by VikramK** [comment]
Thank you so much for this feature.

**Comment by PayshviGhodwall** [comment]
Unable to set selectedTimeSlots..
