### ISSUE TITLE
Ability to select multiple times

### ISSUE THREAD

**Issue by j10sanders** [lrojas94/react-timeslot-calendar#29]
It would be wonderful if a user can select a whole bunch of times, and they will stay highlighted, unless the user clicks on them again.  This way, a user can select a whole range of times they are available. 

Is this already a feature that I am just missing?

**Comment by lrojas94** [comment]
There's a prop called: `maxTimeslots`. You can set that number to a maximum number of timeslot you may allow your user to select. By default this is set to `1`, so feel free to try this out :).

**Comment by j10sanders** [comment]
Perfect.  Thank you!
