### ISSUE TITLE
Change slot duration

### ISSUE THREAD

**Issue by mfaheemakhtar** [lrojas94/react-timeslot-calendar#33]
How can I change the timeslot from 1 hour to 30 minutes?

I tried:

timeslotProps={{
    format: "h:mm",
    showFormat: "h:mm A"
}}

with timeslots={[["9:30", "10:00"], ["10:00", "10:30"], ["18"]]}

This causes a bug and selecting a timeslot selects the whole column.

Any idea?

![image](https://user-images.githubusercontent.com/17894982/45253559-be063b80-b382-11e8-9901-f5333839e8da.png)

**Comment by mfaheemakhtar** [comment]
Looks like the project is dead. :(

BTW! Got it fixed by recreating some functions.

**Comment by ustincameron** [comment]
> Looks like the project is dead. :(
> 
> BTW! Got it fixed by recreating some functions.

Hi, do you mind sharing your updated version? I also need the ability for time-slots that aren't "one hour".

**Comment by mfaheemakhtar** [comment]
I don't have access to that code anymore.

**Comment by AecbAkash** [comment]
hii anyway can you guys help in doing this. Or and alternative plugin that you know which mite help
